server:
    port: 9000
extender:
    defoldSdkPath: /tmp/defoldsdk
spring.http.multipart.max-file-size: 500mb
spring.http.multipart.max-request-size: 500mb

# Don't check for templates on startup.
spring.mustache.check-template-location: false
