
server:
    port: 9000

extender:
    sdk:
        location: /usr/local/extender/sdk
        cache-size: 5
    cache:
        enabled: false
    remote-builder:
        enabled: false

endpoints:
    health:
        sensitive: true
