
server:
    port: 9000

extender:
    sdk:
        location: /var/extender/sdk
        # Slightly bigger than production in order to not remove version controlled SDK
        cache-size: 10
    server:
        http:
            idle-timeout: 600000
    cache:
        enabled: false
        file-size-threshold: 65536
    remote-builder:
        enabled: false
        platforms: ios, osx

spring:
    http:
        multipart:
            enabled: false
            max-file-size: 500mb
            max-request-size: 500mb
    # Don't check for templates on startup
    mustache:
        check-template-location: false

# All management endpoints except simple health status are disabled for security reasons
endpoints:
    enabled: false
    health:
        enabled: true
        sensitive: false

# Suppress info-logging from metrics reporting client
logging.level.okhttp3.OkHttpClient: WARN
# Increase thread name size, to make the job name more visible
logging.pattern.console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.23t]){cyan} %clr(%-40.40c{1.}){blue} %clr(:){red} %clr(%m){faint}%n"

management:
    health:
        diskspace:
            path: /
            threshold: 524288000 #500mb
