
server:
    port: 9000

extender:
    sdk:
        location: /var/extender/sdk
        # Slightly bigger than production in order to not remove version controlled SDK
        cache-size: 10
    server:
        http:
            idle-timeout: 600000
    cache:
        enabled: false
        file-size-threshold: 65536
    remote-builder:
        enabled: false
        platforms: ios, osx

spring:
    http:
        multipart:
            enabled: false
            max-file-size: 500mb
            max-request-size: 500mb
    # Don't check for templates on startup
    mustache:
        check-template-location: false

# All management endpoints except simple health status are disabled for security reasons
endpoints:
    enabled: false
    health:
        enabled: true
        sensitive: false

# Suppress info-logging from metrics reporting client
logging.level.okhttp3.OkHttpClient: WARN

management:
    health:
        diskspace:
            path: /
            threshold: 524288000 #500mb
